apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfc-deployment
  labels:
    app: cfc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cfc
  template:
    metadata:
      labels:
        app: cfc
    spec:
      containers:
      - name: cfc
        image: larslippert/cfc
        ports:
        - containerPort: 8080